#include <map>
namespace Descriptors {
namespace Easings {

const char* name_array[] = {
 "EaseLinearNone",
 "EaseLinearIn",
 "EaseLinearOut",
 "EaseLinearInOut",
 "EaseSineIn",
 "EaseSineOut",
 "EaseSineInOut",
 "EaseCircIn",
 "EaseCircOut",
 "EaseCircInOut",
 "EaseCubicIn",
 "EaseCubicOut",
 "EaseCubicInOut",
 "EaseQuadIn",
 "EaseQuadOut",
 "EaseQuadInOut",
 "EaseExpoIn",
 "EaseExpoOut",
 "EaseExpoInOut",
 "EaseBackIn",
 "EaseBackOut", 
 "EaseBackInOut",
 "EaseBounceOut",
 "EaseBounceIn",
 "EaseBounceInOut",
 "EaseElasticIn",
 "EaseElasticOut",
 "EaseElasticInOut",
};

enum easings {
  EaseLinearNone = 0,
  EaseLinearIn,
  EaseLinearOut,
  EaseLinearInOut,
  EaseSineIn,
  EaseSineOut,
  EaseSineInOut,
  EaseCircIn,
  EaseCircOut,
  EaseCircInOut,
  EaseCubicIn,
  EaseCubicOut,
  EaseCubicInOut,
  EaseQuadIn,
  EaseQuadOut,
  EaseQuadInOut,
  EaseExpoIn,
  EaseExpoOut,
  EaseExpoInOut,
  EaseBackIn,
  EaseBackOut, 
  EaseBackInOut,
  EaseBounceOut,
  EaseBounceIn,
  EaseBounceInOut,
  EaseElasticIn,
  EaseElasticOut,
  EaseElasticInOut,
};

static const std::map<easings, const char *> name({
  {EaseLinearNone,   "EaseLinearNone"},
  {EaseLinearIn,     "EaseLinearIn"},
  {EaseLinearOut,    "EaseLinearOut"},
  {EaseLinearInOut,  "EaseLinearInOut"},
  {EaseSineIn,       "EaseSineIn"},
  {EaseSineOut,      "EaseSineOut"},
  {EaseSineInOut,    "EaseSineInOut"},
  {EaseCircIn,       "EaseCircIn"},
  {EaseCircOut,      "EaseCircOut"},
  {EaseCircInOut,    "EaseCircInOut"},
  {EaseCubicIn,      "EaseCubicIn"},
  {EaseCubicOut,     "EaseCubicOut"},
  {EaseCubicInOut,   "EaseCubicInOut"},
  {EaseQuadIn,       "EaseQuadIn"},
  {EaseQuadOut,      "EaseQuadOut"},
  {EaseQuadInOut,    "EaseQuadInOut"},
  {EaseExpoIn,       "EaseExpoIn"},
  {EaseExpoOut,      "EaseExpoOut"},
  {EaseExpoInOut,    "EaseExpoInOut"},
  {EaseBackIn,       "EaseBackIn"},
  {EaseBackOut,      "EaseBackOut"}, 
  {EaseBackInOut,    "EaseBackInOut"},
  {EaseBounceOut,    "EaseBounceOut"},
  {EaseBounceIn,     "EaseBounceIn"},
  {EaseBounceInOut,  "EaseBounceInOut"},
  {EaseElasticIn,    "EaseElasticIn"},
  {EaseElasticOut,   "EaseElasticOut"},
  {EaseElasticInOut, "EaseElasticInOut"}
});


}
}
